# -*- makefile -*-
# Copyright (C) 2001-2009 KDS software, 42 coffee cups.

##### copy this file to Makefile.def and set BASE path to you own project directory

customer=42
projshort=pumpkin
proj=$(customer)-$(projshort)
ver=$(shell cat .version)
app=pumpkin

BASE=/home/meako/documents/Navch/dyplom/$(proj)
SITE=/home/meako/documents/Navch/dyplom/$(proj)/lib
PYTHONPATH=$(BASE):$(SITE)
PYTHON=$(PYTHONPATH) python

settings=$(app).settings
test_settings=$(app).settings

### Local variables: ***
### compile-command:"make" ***
### tab-width: 2 ***
### End: ***