from pukorators import given,when,then
# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient
client = WindmillTestClient(__name__)

@given("I am on the Google search page")
def go_google():
    client.open(url='http://google.com/')
    client.waits.forPageLoad(timeout='8000')

@when(r'I search for "(?P<query>.*)"')
def search_for_query(query):
    client.click(name='q')
    client.type(text='42 Coffee Cups', name='q')
    client.click(name='btnI')

@then(r'I should see a link to "(?P<expected_url>.*)"')
def should_have_link(expected_url):
    client.waits.forPageLoad(timeout='20000')

